name: Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build executables for all platforms
        run: |
          mkdir -p dist
          bun build index.tsx --compile --minify --sourcemap --target=bun-darwin-arm64 --outfile dist/uv-up-darwin-arm64
          bun build index.tsx --compile --minify --sourcemap --target=bun-darwin-x64 --outfile dist/uv-up-darwin-x64
          bun build index.tsx --compile --minify --sourcemap --target=bun-linux-arm64 --outfile dist/uv-up-linux-arm64
          bun build index.tsx --compile --minify --sourcemap --target=bun-linux-x64 --outfile dist/uv-up-linux-x64

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun add -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm @semantic-release/github
          semantic-release